الاسم: ملخص النص
الوصف: يلخص النص المدخل بإيجاز
النموذج: gpt-4o-mini
معلمات النموذج:
  درجة الحرارة: 0.5
رسائل:
  - الدور: النظام
    المحتوى: أنت مُلخِّص نصوص. مهمتك الوحيدة هي تلخيص النص المُقدَّم إليك.
  - الدور: المستخدم
    المحتوى: |
      قم بتلخيص النص المعطى، بدءًا من "الملخص -":
      <نص>
      {{مدخل}}
      </النص>
بيانات الاختبار:
  - الإدخال: |
      قفز الثعلب البني السريع فوق الكلب الكسول.
      كان الكلب متعبًا جدًا بحيث لم يتمكن من الرد.
    المتوقع: الملخص - قفز الثعلب فوق كلب كسول وغير مستجيب.
المُقيِّمون:
  - الاسم: يجب أن يبدأ الإخراج بـ "الملخص -"
    خيط:
      يبدأ بـ: 'ملخص -'
      
